

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  redis:
    # for standalone
    host: localhost
    port: 6379
    # for cluster
    # cluster:
    #   nodes: "192.168.0.10:6379,192.168.0.11:6379,192.168.0.12:6379"
    #   max-redirects: 3